#!/bin/bash
cd $(dirname $0)/../..

export WORKON_HOME=$(pwd)

source $(which virtualenvwrapper.sh)
if [ $? != 0 ]
then
  echo "Missing prerequisite virtualenvwrapper, bailing out"
  exit 1
fi

if (! test -d "$WORKON_HOME/.notifierlib")
then
  echo "Creating virtual env for .notifierlib"
  mkvirtualenv ".notifierlib"
fi

echo "Working on virtualenv notifierlib"
source "$WORKON_HOME/.notifierlib/bin/activate"

echo "Installing python package requirements.."
pip install -r requirements.txt
